language: python

python:
  - "3.7-dev"

services:
  - postgresql

before_script:
  - psql -c 'create database dev;' -U postgres
  - psql -c 'create database test;' -U postgres


install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - python3 -m unittest
  - coverage run --source=app -m unittest
  - coverage report

after_success:
  - coveralls
  # - codecov
